---
title: "portfolio"
author: "Huong-Giang To"
date: "April 29, 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
set.seed(4051)
load("PortfolioChallenge.Rda")

```

```{r}
X[2,1]
```

```{r}
log_returns = c()
for (i in 2:80){
  for (j in 1:30){
    log_returns <- append(log_returns, log(X[i,j])-log(X[i-1,j])) #natural log
  }
}
log_returns_mtx = matrix(log_returns, nrow=79, ncol=30, byrow=FALSE)
X <- log_returns_mtx
```

```{r}
library(glasso)
Y <- X
Y_train = Y[1:60,]
cmeans <- colMeans(Y_train)
Y_train <- t(t(Y_train)-cmeans)
Y_val = Y[60:79,]
print(dim(Y_val))
Y_cov = cov(Y_train) 
s <- sqrt(diag(Y_cov))
S <- diag(1/s) %*% Y_cov %*% diag(1/s) 
S
```

```{r}
library(emdbook)
print(length(Y_val))
max_loglikelihood <- -100000
max_lambda_idx <- 0
par(mfrow=c(2,2), mar=c(1,1,1,1))
lambda = seq(from=0,to=0.3,by=0.001)
fit.glasso <- glassopath(s=S, rholist = lambda, penalize.diagonal = FALSE, trace=0)

for(i in 1:length(lambda)){
theta.hat <- fit.glasso$wi[,,i]
#print(theta.hat)

adjacency.matrix <- ifelse(abs(theta.hat)<=1e-5, 0, 1)

#colnames <- colnames(stock)[-1]
#rownames(adjacency.matrix) <- colnames(adjacency.matrix) <- colnames

est_cov <- diag(s)%*%fit.glasso$w[,,i]%*%diag(s)
loglikelihood <- sum(dmvnorm(Y_val, mu = cmeans, est_cov, log = TRUE))
if (loglikelihood > max_loglikelihood){
  max_loglikelihood <- loglikelihood
  best_lambda <- lambda[i]
}

#graph <- graph_from_adjacency_matrix(adjmatrix=adjacency.matrix,mode='undirected',diag=FALSE)
#layout <- layout_in_circle(graph)
#title <- paste0('Graphical Gaussian Model - Lambda = ', lambda[i])
#plot(graph, layout=layout, main=title)
}

#print(max_lambda_idx)
print(best_lambda)
```

```{r}
Y_cov_final = cov(Y) #is this the estimated correlation matrix?
s <- sqrt(diag(Y_cov_final))
S <- diag(1/s) %*% Y_cov_final %*% diag(1/s) #this is the estimated correlation matrix

fit.glasso <- glasso(s =S, rho=best_lambda)
theta.hat <- fit.glasso$wi
adjacency.matrix <- ifelse(abs(theta.hat)<=1e-5, 0, 1)
theta.hat
#adjacency.matrix[1:3, 1:3]
#colnames <- colnames(stock)[-1]
#rownames(adjacency.matrix) <- colnames(adjacency.matrix) <- colnames
graph <- graph_from_adjacency_matrix(adjmatrix=adjacency.matrix,
mode='undirected',
diag=FALSE)
## specify a layout, use a circle layout here.
layout <- layout_in_circle(graph)
plot(graph, layout=layout, main='Graphical Gaussian Model')
```

```{r}
stock_cor = diag(s) %*% fit.glasso$w %*% diag(s)
stock_cor
```

```{r}
Markowitz <- function(mu, Sigma, gamma){
  n <- length(mu)
  w <- Variable(n)
  ret <- t(mu) %*% w
  risk <- quad_form(w, Sigma)
  constraints <- list(w >= 0, sum(w) == 1)
  ### solve the problem by CVXR
  objective <- ret - gamma * risk
  prob <- Problem(Maximize(objective), constraints)
  result <- solve(prob)
  ### results
  risk <- result$getValue(sqrt(risk)) ### the standard deviation
  exp.return <- result$getValue(ret) ### the expected return
  port.w <- result$getValue(w) ### the w vector
  return(list(port.w=port.w,risk=risk,exp.return=exp.return))
}
```

```{r}
expected_returns <- colMeans(X)
expected_returns
```

```{r}
result <- Markowitz(expected_returns, stock_cor, 100)
result$risk
```

```{r}
result$exp.return
```

```{r}
p <- 30
SAMPLES <- 200
gammas <- 10^seq(-1, 3, length.out = SAMPLES)
ret_data <- rep(0, SAMPLES)
risk_data <- rep(0, SAMPLES)
w_data <- matrix(0, nrow = SAMPLES, ncol = p )
```


```{r}
for(i in seq_along(gammas)) { # seq_along(gammas) = 1:200
gamma <- gammas[i]
result <- Markowitz(expected_returns, stock_cor, gamma)
risk_data[i] <- result$risk
ret_data[i] <- result$exp.return
w_data[i,] <- result$port.w

}
```

```{r}
plot(x=risk_data,y=ret_data,type="l",
ylab="expected return",xlab="risk",lwd=2,cex.lab=1.4)
```

```{r}
w_data
```

pick return ~0.017
```{r}
ret_data
```

ideces: 131->148

```{r}
risk_data[131:148]
```

```{r}
dy <- diff(ret_data)
dy
```

```{r}
min(dy)
```

```{r}
sum(w_data[141,])

```

```{r}
ret_data[141]
```

expected return with naive method
```{r}
asset_mean_returns <- apply(log_returns_mtx, 2, mean)

# Calculate the mean return of the portfolio for each time period
portfolio_mean_returns <- mean(asset_mean_returns)

# Print the portfolio mean returns for each time period
print(portfolio_mean_returns)
```

```{r}
w <- w_data[141,]
save(w, file = "w.Rda")

```

Maybe use PCA? -> goal find linear comination


